In [93]:
import pandas as pd
import numpy as np

In [23]:
doc = "D.S. is fun!\nIt's  true."
print(doc)

D.S. is fun!
It's  true.


In [24]:
'|'.join(doc)

"D|.|S|.| |i|s| |f|u|n|!|\n|I|t|'|s| | |t|r|u|e|."

In [26]:
import re

# Find all of the whitespaces in doc
print(doc)

re.findall('\s+',doc)

D.S. is fun!
It's  true.


[' ', ' ', '\n', '  ']

In [27]:
re.split(r'\s+', doc)

['D.S.', 'is', 'fun!', "It's", 'true.']

In [203]:
re.findall(r'\b\w\w+\b', doc)

['is', 'fun', 'It', 'true']

In [219]:
re.findall(r'\b\w\w+\b', re.sub(r'D\.S\.','Data Science',doc))

['Data', 'Science', 'is', 'fun', 'It', 'true']

In [205]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [206]:
X = cv.fit_transform([doc])

In [207]:
cv.vocabulary_

{'is': 1, 'fun': 0, 'it': 2, 'true': 3}

In [46]:
cv = CountVectorizer(token_pattern=r'\b\S\S+\b')

In [47]:
X = cv.fit_transform([doc])

In [48]:
cv.vocabulary_

{'d.s': 0, 'is': 2, 'fun': 1, "it's": 3, 'true': 4}

In [49]:
re.sub(r'\W+',' ',doc)

'D S is fun It s true '

In [51]:
re.sub(r'\s+',' ',re.sub(r'\W+',' ',doc))

'D S is fun It s true '

In [52]:
import spacy

In [56]:
%run -m spacy download en_core_web_sm


    Linking successful
    /home/bgibson/anaconda3/envs/eods-f19/lib/python3.7/site-packages/en_core_web_sm
    -->
    /home/bgibson/anaconda3/envs/eods-f19/lib/python3.7/site-packages/spacy/data/en_core_web_sm

    You can now load the model via spacy.load('en_core_web_sm')



In [57]:
nlp = spacy.load("en_core_web_sm")

In [210]:
parsed = nlp(doc)

In [214]:
'|'.join([token.text for token in parsed])

"D.S.|is|fun|!|\n|It|'s| |true|."

In [218]:
sorted(re.findall(r'\b\w\w+\b', re.sub(r'D\.S\.','Data Science',doc).lower()))

['data', 'fun', 'is', 'it', 'science', 'true']

In [269]:
docs = ['D.S. is fun!','It is true.']

In [270]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
X = cv.fit_transform(docs)

cv.vocabulary_

{'is': 1, 'fun': 0, 'it': 2, 'true': 3}

In [271]:
cv = CountVectorizer(lowercase=True,
                     min_df=1,
                     max_df=1.0,
                     token_pattern='\\b\\S\\S+\\b',
                     ngram_range=(1,2),
                     stop_words='english')
X = cv.fit_transform(docs)
cv.vocabulary_

{'d.s': 0, 'fun': 2, 'd.s fun': 1, 'true': 3}

In [272]:
sorted([(y,x) for x,y in cv.vocabulary_.items()])

[(0, 'd.s'), (1, 'd.s fun'), (2, 'fun'), (3, 'true')]

In [273]:
X

<2x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [274]:
X.todense()

matrix([[1, 1, 1, 0],
        [0, 0, 0, 1]])

In [288]:
docs = ['First sentence is a test.','Second sentence is also a test.']

In [306]:
%pprint off

Pretty printing has been turned OFF


In [310]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(token_pattern='\\b\\S\\S+\\b',
                        stop_words=['is'],
                        norm=False,
                        smooth_idf=False
                       )
X = tfidf.fit_transform(docs)

sorted([(y,x) for x,y in tfidf.vocabulary_.items()])

[(0, 'also'), (1, 'first'), (2, 'second'), (3, 'sentence'), (4, 'test')]

In [311]:
X.todense()

matrix([[0.        , 1.69314718, 0.        , 1.        , 1.        ],
        [1.69314718, 0.        , 1.69314718, 1.        , 1.        ]])

In [312]:
nlp = spacy.load("en_core_web_sm")
doc = nlp("Apple is looking at buying U.K. startup for $1 billion")

In [334]:
print(f"{'text':7s} {'lemma':7s} {'pos':5s} {'is_stop'}")
print('-'*30)
for token in doc:
    print(f'{token.text:7s} {token.lemma_:7s} {token.pos_:5s} {token.is_stop}')

text    lemma   pos   is_stop
------------------------------
Apple   apple   PROPN False
is      be      VERB  True
looking look    VERB  False
at      at      ADP   True
buying  buy     VERB  False
U.K.    u.k.    PROPN False
startup startup NOUN  False
for     for     ADP   True
$       $       SYM   False
1       1       NUM   False
billion billion NUM   False


In [329]:
from spacy import displacy
displacy.render(doc, jupyter=True) # serve(doc, style="dep", page=False)

In [338]:
[(ent.text,ent.label_) for ent in doc.ents]

[('Apple', 'ORG'), ('U.K.', 'GPE'), ('$1 billion', 'MONEY')]

In [358]:
# Note: this takes a while!
%run -m spacy download en_core_web_md 


    Linking successful
    /home/bgibson/anaconda3/envs/eods-f19/lib/python3.7/site-packages/en_core_web_md
    -->
    /home/bgibson/anaconda3/envs/eods-f19/lib/python3.7/site-packages/spacy/data/en_core_web_md

    You can now load the model via spacy.load('en_core_web_md')



In [367]:
nlp = spacy.load('en_core_web_md') # lg has larger vocabulary

In [368]:
doc = nlp('Baseball is played on a diamond.')

In [393]:
doc[0].text,doc[0].vector.shape,list(doc[0].vector[:3])

('Baseball', (300,), [0.55838, 0.42791, -0.11687])

In [394]:
for token in doc:
    print(f'{token.text:8s} {token.vector_norm:.3f} {token.is_oov}')

Baseball 7.319 False
is       4.890 False
played   6.522 False
on       5.218 False
a        5.307 False
diamond  7.293 False
.        4.932 False


In [380]:
docs = list(nlp.pipe(['Baseball is played on a diamond.',
                      'Hockey is played on ice.',
                      'Diamonds are clear as ice.']))

In [397]:
%pprint
[['{:.2f}'.format(docs[i].similarity(docs[j])) for j in range(3)]
 for i in range(3)]

Pretty printing has been turned OFF


[['1.00', '0.85', '0.76'], ['0.85', '1.00', '0.77'], ['0.76', '0.77', '1.00']]

---

In [169]:
from sklearn.datasets import load_files

movies = load_files('/home/bgibson/nltk_data/corpora/movie_reviews')

In [173]:
movies.data[0][:500]

b"arnold schwarzenegger has been an icon for action enthusiasts , since the late 80's , but lately his films have been very sloppy and the one-liners are getting worse . \nit's hard seeing arnold as mr . freeze in batman and robin , especially when he says tons of ice jokes , but hey he got 15 million , what's it matter to him ? \nonce again arnold has signed to do another expensive blockbuster , that can't compare with the likes of the terminator series , true lies and even eraser . \nin this so cal"

In [174]:
movies.target[:50]

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1])

---

In [155]:
import pandas as pd

df_house = pd.read_csv('../data/house_sales_subset_normed.csv',index_col=0)
df = df_house[['SqFtTotLiving_norm','SqFtLot_norm','AdjSalePrice_norm']].iloc[:10]
print(df.head())

   SqFtTotLiving_norm  SqFtLot_norm  AdjSalePrice_norm
0            0.349914      0.654181          -0.798237
3            1.225407      0.442910          -0.309217
4           -0.394254      0.443470          -0.811184
5           -1.258803     -1.685468          -0.414055
7           -0.241043      2.133356          -0.629701


In [156]:
# using euclidean distance
from sklearn.metrics.pairwise import euclidean_distances

# calculate all pairwise distances between houses
dists = euclidean_distances(df)
dists.shape

(10, 10)

In [157]:
# find houses similar to this house
query_idx = 5
df.iloc[query_idx]

SqFtTotLiving_norm   -1.193141
SqFtLot_norm         -0.478846
AdjSalePrice_norm    -1.039064
Name: 8, dtype: float64

In [158]:
# these are all distance scores for query house
[f'{x:0.1f}' for x in dists[query_idx]]

['1.9', '2.7', '1.2', '1.4', '2.8', '0.0', '2.0', '2.1', '1.0', '0.4']

In [160]:
# find indexes of best scores (for distances, want ascending)
best_idxs_asc = np.argsort(dists[query_idx])
best_idxs_asc

array([5, 9, 8, 2, 3, 0, 6, 7, 1, 4])

In [161]:
# the top 10 recommendations
list(zip(best_idxs_asc,sorted(dists[query_idx])))

[(5, 0.0),
 (9, 0.36454193975111393),
 (8, 0.96489046966839),
 (2, 1.2412959364891165),
 (3, 1.3604716337327696),
 (0, 1.929447464433964),
 (6, 1.9964107048046749),
 (7, 2.0989248372129903),
 (1, 2.6891791893333212),
 (4, 2.810278966827491)]

In [110]:
# what if these were similarities instead of differences?
# would need to reverse this
best_idxs_desc = best_idxs_asc[::-1]

In [119]:
# from Data Science from Scratch by Joel Grus
#https://github.com/joelgrus/data-science-from-scratch.git

users_interests = [
    ["Hadoop", "Big Data", "HBase", "Java", "Spark", "Storm", "Cassandra"],
    ["NoSQL", "MongoDB", "Cassandra", "HBase", "Postgres"],
    ["Python", "scikit-learn", "scipy", "numpy", "statsmodels", "pandas"],
    ["R", "Python", "statistics", "regression", "probability"],
    ["machine learning", "regression", "decision trees", "libsvm"],
    ["Python", "R", "Java", "C++", "Haskell", "programming languages"],
    ["statistics", "probability", "mathematics", "theory"],
    ["machine learning", "scikit-learn", "Mahout", "neural networks"],
    ["neural networks", "deep learning", "Big Data", "artificial intelligence"],
    ["Hadoop", "Java", "MapReduce", "Big Data"],
    ["statistics", "R", "statsmodels"],
    ["C++", "deep learning", "artificial intelligence", "probability"],
    ["pandas", "R", "Python"],
    ["databases", "HBase", "Postgres", "MySQL", "MongoDB"],
    ["libsvm", "regression", "support vector machines"]
]

In [120]:
# interests of user0
users_interests[0]

['Hadoop', 'Big Data', 'HBase', 'Java', 'Spark', 'Storm', 'Cassandra']

In [121]:
# want a sorted list of unique interests (here using set)
unique_interests = sorted({interest 
                           for user_interests in users_interests
                           for interest in user_interests})

In [122]:
unique_interests[:5]

['Big Data', 'C++', 'Cassandra', 'HBase', 'Hadoop']

In [123]:
# have user interests and unique interests (columns)

from sklearn.preprocessing import MultiLabelBinarizer
# Transform between lists of strings and fixed length lists of ints

In [124]:
mlb = MultiLabelBinarizer(classes=unique_interests)

In [125]:
user_interest_matrix = mlb.fit_transform(users_interests)

In [126]:
user_interest_matrix[0]

array([1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [190]:
mlb.classes_[np.where(user_interest_matrix[0])].tolist()

['Big Data', 'Cassandra', 'HBase', 'Hadoop', 'Java', 'Spark', 'Storm']

In [188]:
sorted(users_interests[0])

['Big Data', 'Cassandra', 'HBase', 'Hadoop', 'Java', 'Spark', 'Storm']

In [191]:
# do the positions of 1s match the user0 interests?
assert mlb.classes_[np.where(user_interest_matrix[0])].tolist() == sorted(users_interests[0])

In [128]:
# need to find the similarities (1-distance) between users based on interests

from sklearn.metrics.pairwise import cosine_similarity

In [129]:
user_similarities = cosine_similarity(user_interest_matrix)

In [192]:
user_similarities[0]

array([1.        , 0.3380617 , 0.        , 0.        , 0.        ,
       0.15430335, 0.        , 0.        , 0.18898224, 0.56694671,
       0.        , 0.        , 0.        , 0.16903085, 0.        ])

In [196]:
# what users does user0 share interests with?
np.nonzero(user_similarities[0])[0]

array([ 0,  1,  5,  8,  9, 13])

In [197]:
# return a sorted list of users based on similarity
# skip not query user and similarity == 0
def most_similar_users_to(query_idx):
    users_scores = [(idx,sim) 
                    for idx,sim in enumerate(user_similarities[query_idx]) 
                    if idx != query_idx and sim > 0]
    return sorted(users_scores, key=lambda x:x[1])

In [198]:
most_similar_users_to(0)

[(5, 0.1543033499620919),
 (13, 0.1690308509457033),
 (8, 0.1889822365046136),
 (1, 0.3380617018914066),
 (9, 0.5669467095138407)]

In [199]:
most_similar_users_to(5)

[(0, 0.1543033499620919),
 (2, 0.1666666666666667),
 (9, 0.20412414523193154),
 (11, 0.20412414523193154),
 (10, 0.2357022603955159),
 (3, 0.36514837167011077),
 (12, 0.4714045207910318)]

In [133]:
# return the interests of other users
# weight is sum of similarity to other users

from collections import defaultdict

def user_based_suggestions(idx):
    suggestions = defaultdict(float)
    
    # iterate over interests of similar users
    for other_idx, sim in most_similar_users_to(idx):
        for interest in users_interests[other_idx]:
            suggestions[interest] += sim
            
    # sort suggestions based on weight
    suggestions = sorted(suggestions.items(),
                        key=lambda x:x[1],
                        reverse=True)
    
    # return only new interests
    return [(suggestion,weight)
            for suggestion,weight in suggestions
            if suggestion not in users_interests[idx]]

In [134]:
# reminder: original interests
users_interests[0]

['Hadoop', 'Big Data', 'HBase', 'Java', 'Spark', 'Storm', 'Cassandra']

In [135]:
# top 5 new recommended interests
user_based_suggestions(0)[:5]

[('MapReduce', 0.5669467095138407),
 ('Postgres', 0.50709255283711),
 ('MongoDB', 0.50709255283711),
 ('NoSQL', 0.3380617018914066),
 ('neural networks', 0.1889822365046136)]